### PR TITLE
deal with the response in the right way

### LINKED ISSUE #16: Faraday middlware does not work with parallel requests
The Faraday middlware will always return a `NullResponse` to wrap the the return value if the request uses the `connection.in_parallel do ... end` way of running the requests. The reason being the when run in parallel the requests always return `nil` while in the block and will resolve later to their result when the block is done see [the faraday wiki](https://github.com/lostisland/faraday/wiki/Parallel-requests).

### PR DESCRIPTION
**Pull request by sideshowcoder**
since in parrallel returns futures for the response while running them
in parallel so we need to listen to the on_complete

fixes #16

### CODE REVIEW

**Comment by sideshowcoder** [comment]
@yarmand can you take a look at this with me on monday as well, I would love to get it out next week as a point release because it is blocking internal http_clients :(

File: lib/circuitbox/faraday_middleware.rb [hunk 1]
```diff
@@ -47,6 +49,11 @@ def identifier
 
     private
 
+    def check_circuit_open!(env)
```
Comment (nickcampbell18) [inline lib/circuitbox/faraday_middleware.rb]: Why is this a bang method?

File: lib/circuitbox/faraday_middleware.rb [hunk 2]
```diff
@@ -75,6 +82,15 @@ def default_value
                        end
     end
 
+    def success?(env)
+      case env.status
+      when 200..399
+        true
+      when 400..599
+        false
+      end
```
Comment (nickcampbell18) [inline lib/circuitbox/faraday_middleware.rb]: There is no default answer. What if the response is `1xx` (unlikely)?

File: lib/circuitbox/faraday_middleware.rb (hunk 1 above)
Comment (sideshowcoder) [inline lib/circuitbox/faraday_middleware.rb]: because it raises an exception, as `run!` might raise one.

File: lib/circuitbox/faraday_middleware.rb (hunk 2 above)
Comment (sideshowcoder) [inline lib/circuitbox/faraday_middleware.rb]: good point...
