### PR TITLE
Fix issue #28

### LINKED ISSUE #28: Faraday Middleware creating two requests
faraday_middleware.rb line 32
```
def call(request_env)
      service_response = nil
      check_circuit_open!(request_env)
      circuit(request_env).run!(run_options(request_env)) do
        @app.call(request_env).on_complete do |env|
          service_response = Faraday::Response.new(env)
          raise RequestFailed if open_circuit?(service_response)
        end
      end
```

The check circuit runs the request which causes a successful request to be made and logged. Every request that fails first gets logged as successful and then as failed. Its doubling the number of requests. This affects the volume_threshold and stats. Looks like line 32 can just be deleted.

### PR DESCRIPTION
**Pull request by chiefcll**
fixes #28

### CODE REVIEW

File: lib/circuitbox/faraday_middleware.rb [hunk 1]
```diff
@@ -29,7 +29,6 @@ def initialize(app, opts = {})
 
     def call(request_env)
       service_response = nil
-      check_circuit_open!(request_env)
```
Comment (sideshowcoder) [inline lib/circuitbox/faraday_middleware.rb]: What was I thinking when I wrote this? I guess we'll never know good catch :+1:

**Comment by sideshowcoder** [comment]
This looks good to me! @nronas is going to give it a secound look.

File: test/integration/faraday_middleware_test.rb [hunk 2]
```diff
@@ -22,6 +22,30 @@ def teardown
       Circuitbox.reset
     end
 
+    def open_circuit
```
Comment (nronas) [inline test/integration/faraday_middleware_test.rb]: It would be good to hide that method on the private api of the test if want to use it only in the scope of this test. If we need to use it as a helper method then best place would be the test_helper.

Comment (sideshowcoder) [inline test/integration/faraday_middleware_test.rb]: Yes you are right, we should move that to the `integration_helper.rb` I think as it is very useful, and should be part of the helper suite. @chiefcll do you fancy moving it? Otherwise I'm happy to do it after merge as well.

File: test/integration/faraday_middleware_test.rb [hunk 3]
```diff
@@ -22,6 +22,30 @@ def teardown
...
+      volume_threshold = Circuitbox['test'].option_value(:volume_threshold)
+      (volume_threshold + 1).times { @connection.get(@failure_url) }
+    end
+
+    def test_failure_count
```
Comment (sideshowcoder) [inline test/integration/faraday_middleware_test.rb]: I know why those tests are here but I feel like they assert to low level for an integration test. Could we create one like

```
def test_circuit_does_not_open_for_below_threshhold_failed_requests
  5.times { @connection.get(@failure_url) }
  assert_equal @connection.get(@success_url).status, 200
end

File: test/integration/faraday_middleware_test.rb [hunk 4]
```diff
@@ -22,6 +22,30 @@ def teardown
...
+      6.times { @connection.get(@failure_url) }
+      assert_equal Circuitbox['localhost'].failure_count, 6
+      assert_equal Circuitbox['localhost'].success_count, 0
+    end
+
+    def test_success_count
```
Comment (sideshowcoder) [inline test/integration/faraday_middleware_test.rb]: see `test_failure_count`

File: test/integration/faraday_middleware_test.rb [hunk 5]
```diff
@@ -22,6 +22,30 @@ def teardown
...
+      6.times { @connection.get(@success_url) }
+      assert_equal Circuitbox['localhost'].success_count, 6
+      assert_equal Circuitbox['localhost'].failure_count, 0
+    end
+
+    def test_multiple_calls_count
```
Comment (sideshowcoder) [inline test/integration/faraday_middleware_test.rb]: see `test_failure_count`

**Comment by sideshowcoder** [comment]
Ok taking a deeper look at the tests I had some more small comments, I'm happy to merge this besides those, but it's fixable after merge as well @chiefcll if you like :+1: Thanks so much for your work!

**Comment by sideshowcoder** [comment]
I decided to merge this and cleanup the small changes after since I wanted to try it out against an app. See https://github.com/yammer/circuitbox/pull/32
